# Generated by Django 5.0.1 on 2024-01-25 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('weather', models.BooleanField(default=True)),
                ('weatherData', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.BooleanField(default=False)),
                ('emailData', models.CharField(blank=True, max_length=50, null=True)),
                ('emailPriority', models.CharField(max_length=50)),
                ('eta', models.BooleanField(default=False)),
                ('etaData', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
